export const defaultSettings: SettingsState = {
  backgroundRichness: "rich",
  syncSettings: true,
  navigationBar: "flexible",
  floatingCodeSpeed: 1800,
  disableCenterPainting: false,
  disableComments: false,
  disableGestures: false,
  disableSerifFont: false,
  disableEntryPopUp: false,
  disableBackgroundBlur: false,
  enableGallery: false,
  preferredManagementTheme: "zimo",
  enableHalloweenEffect: false,
  disableSoundEffect: false,
};
